### PR TITLE
TR rm 1.0.0 and new test dcc

### PR DESCRIPTION
**Pull request by sahinguney**

### CODE REVIEW

**Comment by mkubicek-dtc** [comment]
@sahinguney with this you remove the 1.0.0 REC, TEST, VAC DCCs and add one single 1.3.0 TEST DCC. Is this what you intended? This signals to other countries that you have issued only 1.3.0 TEST DCCs to your citizens (no REC, no VAC and no DCCs with schema 1.0.0).

**Comment by TKlauenberg** [comment]
Android 1.1.12 🆗

**Comment by niklasdewes** [comment]
iOS 1.1.6.1 (7) 🆗

**Comment by sahinguney** [comment]
@mkubicek-dtc that's right, as you know we are not in production yet. So, we didn't issue any certificate to our citizens. All the certificates will be issued in 1.3.0 schema format when we go for production. For this reason, we think it is not necessary to maintain 1.0.0 schema versions.

**Pull request merged**
