### PR TITLE
DK: Version 1.3.0 QR codes

### PR DESCRIPTION
**Pull request by jvitrifork**

### CODE REVIEW

**Comment by chrloch** [comment]
The PNG files should be in the folder 1.3.0 and there should be a README.md instead of the json files.

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.0.7.-acc : all certs are **valid**

**Comment by jvitrifork** [comment]
@chrloch fixed

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.0.7.-acc : all 4 certs are **valid**

**Comment by RKlaus-tsi** [comment]
iOS 1.0.5 all 4 codes are valid

**Pull request merged**
