### PR TITLE
SI: All codes should be working now (NB ACC)

### PR DESCRIPTION
**Pull request by jozemlakar**

### CODE REVIEW

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.0.7.-acc:

- 1.3.0/ : REC, VAC, TEST-AG, TEST-PCR are **valid**
- 1.3.0/special cases : TEST-AG, TEST-PCR : Cryptographic signature invalid (no type selection)

**Comment by jozemlakar** [comment]
1.3.0/special cases : TEST-AG, TEST-PCR
These were deleted by this PR. Or am I missing something.

**Comment by kerstin-oppermann-tsi** [comment]
> 1.3.0/special cases : TEST-AG, TEST-PCR
> These were deleted by this PR. Or am I missing something.

Yes, I did not checked this correctly, only scanned the codes. The codes are marked as deleted.

**Comment by RKlaus-tsi** [comment]
iOS 1.0.5: 2 new codes and 2 old codes shown as valid

**Pull request merged**
