### PR TITLE
SI: Schema version 1.3.0

### PR DESCRIPTION
**Pull request by chrloch**
Submitted via email by Joze.Mlakar@ixtlan-team.si

### CODE REVIEW

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.0.7.-acc:

- TEST-AG, TEST-PCR : Cryptographic signature **invalid** (without showing what cert it is (Test/Vac/Rec))
- VAC, REC - **valid**

**Comment by RKlaus-tsi** [comment]
iOS 1.0.5:

TEST-AG, TEST-PCR :  invalid (no entries in the certificate)
VAC, REC - shown as valid

**Comment by chrloch** [comment]
Schema validation passed for the problematic TEST certs: 

/TEST-PCR.png] {1: 'SI', 4: 1632302125, 6: 1624526125, -260: {1: {'t': [{'ci': 'URN:UVCI:01:SI:C58058DC327FB214E053#2', 'co': 'SI', 'is': 'Nacionalni inštitut za javno zdravje', 'sc': '2021-06-16T22:00:00Z', 'tg': '840539006', 'tr': '260415000', 'tt': 'LP6464-4'}], 'dob': '1965-11-06', 'nam': {'fn': 'GULIKOZA', 'gn': 'JOZA', 'fnt': 'GULIKOZA', 'gnt': 'JOZA'}, 'ver': '1.3.0'}}}
Schema validation passed

/TEST-AG.png] {1: 'SI', 4: 1632302422, 6: 1624526422, -260: {1: {'t': [{'ci': 'URN:UVCI:01:SI:C58058BFDE63B20AE053#:', 'co': 'SI', 'is': 'Nacionalni inštitut za javno zdravje', 'nm': 'AMEDA Labordiagnostik GmbH, AMP Rapid Test SARS-CoV-2 Ag', 'sc': '2021-06-18T06:35:40Z', 'tg': '840539006', 'tr': '260415000', 'tt': 'LP217198-3'}], 'dob': '1941-01-18', 'nam': {'fn': 'GULIKOZA', 'gn': 'JOZA', 'fnt': 'GULIKOZA', 'gnt': 'JOZA'}, 'ver': '1.3.0'}}}
Schema validation passed

**Comment by chrloch** [comment]
TEST codes moved to special cases because signature and schema verification PASSED and only mobile device checks failed

**Pull request merged**
