### PR TITLE
PL: Add special cases (date-time)

### PR DESCRIPTION
**Pull request by mkubicek-dtc**

### CODE REVIEW

**Comment by RKlaus-tsi** [comment]
check with android 1.0.4-acc, the verifier app shows for all 3 Code "valid"
check with iOS 1.0.4.1, all 3 codes could not be scanned

**Comment by mkubicek-dtc** [comment]
@SchulzeStTSI: Please merge as soon as DEV is informed.

**Comment by mkubicek-dtc** [comment]
Hi @RKlaus-tsi 
Please check again with new iOS version.

**Comment by RKlaus-tsi** [comment]
iOS 1.0.5: App shows all 3 codes as valid

**Pull request merged**
