### PR TITLE
ES: QR codes for Validation Cycle 

### PR DESCRIPTION
**Pull request by Santivicen**

### CODE REVIEW

**Comment by chrloch** [comment]
DSC is not on ACC environment yet. Please upload DSC
(Automatic checks can't access ACC and skip signature verification therefore)

**Comment by Santivicen** [comment]
> DSC is not on ACC environment yet. Please upload DSC (Automatic checks can't access ACC and skip signature verification therefore)

So sorry, I had upload right now.

Please could you check now?

**Comment by chrloch** [comment]
Codes are 🆗  now

For the invalidated DCC: 
You currently have no "invalidation rule" uploaded, did you understand the case as "fails a business rule?" (because the DCCs does that, I just want to understand if it's intentional)

**Comment by Santivicen** [comment]
> Codes are 🆗 now
> 
> For the invalidated DCC: You currently have no "invalidation rule" uploaded, did you understand the case as "fails a business rule?" (because the DCCs does that, I just want to understand if it's intentional)

Right now our rules are not updated. I had upload on specialCases one CCD created on 01-01-2021, that must be invalid. 

If I have to put at same level than the opthers, please tell me, and I will update it asap.

**Comment by chrloch** [comment]
@Santivicen 
No, I will just remove the "invalidated" code because it's a mix-up of "invalid" and "invalidated"
With "invalidated" was meant: Code is valid, but a rule declares it invalid because of special circumstances (e.g. UVCI range of fraudulent issuers)

**Pull request merged**
