### PR TITLE
Add Scottish Vac Cert

### PR DESCRIPTION
**Pull request by andypandy47**

### CODE REVIEW

**Comment by chrloch** [comment]
KID of DSC not found on ACC

**Comment by mkubicek-dtc** [comment]
@andypandy47 Please upload corresponding DSCs on the ACC Gateway.

**Comment by andypandy47** [comment]
Corresponding DSC should have been uploaded friday afternoon. Thanks

**Comment by chrloch** [comment]
DSC successfully found on ACC
DCC is expired. Validity only set to 4 days. Intentional?

**Comment by andypandy47** [comment]
@chrloch should be updated with a longer expiry now

**Comment by chrloch** [comment]
Thanks
Verifier 1.2.2 scans 🆗

**Pull request merged**
