### PR TITLE
NO: Add 1.3.0 test data

### PR DESCRIPTION
**Pull request by mkubicek-dtc**

### CODE REVIEW

**Comment by mkubicek-dtc** [comment]
Hi @RKlaus-tsi, please verify.

**Comment by RKlaus-tsi** [comment]
Android 1.0.5: all 3 certificates shown as invalid. REC certificate is shown as invalid. Vac and Test are expired
iOS 1.0.5: all 3 certificates shown as invalid and signature not valid

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.06.-acc:
REC.png  - Verification failed (without showing what it is (Rec,Vac,Test))
TEST.png - Certificate expired
VAC.png - Verification failed

**Comment by kerstin-oppermann-tsi** [comment]
in the readme: 
Used for productive DCCs issuance
* From: **24.06.2021**
* Until:
* 
.... seems they must be valid only from tomorrow

**Comment by mkubicek-dtc** [comment]
Replaced by https://github.com/eu-digital-green-certificates/dcc-quality-assurance/pull/34

**Pull request closed without merging**
