### PR TITLE
1.3.0 HR test codes uploaded 

### PR DESCRIPTION
**Pull request by kristinaleko**

### CODE REVIEW

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.0.7.-acc : all codes are valid

**Comment by kristinaleko** [comment]
@kerstin-oppermann-tsi  thx Kerstin! the changes can be pulled to main?

**Comment by RKlaus-tsi** [comment]
iOS 1.0.5: all codes shown as valid

**Comment by kerstin-oppermann-tsi** [comment]
> @kerstin-oppermann-tsi thx Kerstin! the changes can be pulled to main?

@chrloch  Can you do this?

**Pull request merged**
