### PR TITLE
SI: following valuesets appropriately

### PR DESCRIPTION
**Pull request by jozemlakar**

### CODE REVIEW

**Review by chrloch — APPROVED** [review]

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.0.7.-acc : all codes are **valid** 

iOS 1.1.3. : all codes are **valid**  

(special cases that are invalid are deleted with this PR - correct @jozemlakar ?)

**Comment by jozemlakar** [comment]
> Android 1.0.7.-acc : all codes are **valid**
> 
> iOS 1.1.3. : all codes are **valid**
> 
> (special cases that are invalid are deleted with this PR - correct @jozemlakar ?)

@kerstin-oppermann-tsi in fact no, special cases that were invalid were deleted with the previous PR already.

**Comment by kerstin-oppermann-tsi** [comment]
@jozemlakar So I have a little understanding problem. Should the files
https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/8ad35c88d424ecb450ded68a320c47bdd1000752/SI/1.3.0/specialcases/TEST-PCR.png 
https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/8ad35c88d424ecb450ded68a320c47bdd1000752/SI/1.3.0/specialcases/TEST-PCR.png
to be merged? Both certs are cryptographic signature invalid

**Comment by jozemlakar** [comment]
> @jozemlakar So I have a little understanding problem. Should the files
> https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/8ad35c88d424ecb450ded68a320c47bdd1000752/SI/1.3.0/specialcases/TEST-PCR.png
> https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/8ad35c88d424ecb450ded68a320c47bdd1000752/SI/1.3.0/specialcases/TEST-PCR.png
> to be merged by this PR or not? Both certs are cryptographic signature invalid

@kerstin-oppermann-tsi both files are already deleted in main branch and are not part of this PR. I really do not understand why we are talking about this.

https://github.com/eu-digital-green-certificates/dcc-quality-assurance/tree/main/SI/1.3.0

**Comment by kerstin-oppermann-tsi** [comment]
@jozemlakar sorry for that confusing conversation - was my mistake and misunderstanding :(

**Comment by jozemlakar** [comment]
No worries, happy we got it resolved. Have a great day.

**Comment by kerstin-oppermann-tsi** [comment]
> No worries, happy we got it resolved. Have a great day.

Thx, the same to you.

**Pull request merged**
