### PR TITLE
BG: Add special cases (datetime, null)

### PR DESCRIPTION
**Pull request by mkubicek-dtc**

### CODE REVIEW

**Comment by RKlaus-tsi** [comment]
Android V1.0.4: Validator app shows "valid" for all 2 certs
iOS V1.0.4.1 Validator could not scan codes

**Comment by mkubicek-dtc** [comment]
A number of BG DCCs not adhering to the schema have been issued in production:
* datetime instead of date
* null values for non-existing properties

Decoded VAC-NULL-DATETIME.png:
```
EU Digital Covid Certificate Verifiable QR
{
  "tag": 18,
  "value": [
    { "Map": [ [ 1, -7 ] ] },
    { "Map": [ [ 4, "STPDGKKF4N8" ] ] },
    {
      "Map": [
        [ 1, "BG" ],
        [ 4, 1654178876 ],
        [ 6, 1622642876 ],
        [
          -260,
          {
            "Map": [
              [
                1,
                {
                  "r": null,
                  "t": null,
                  "v": [
                    {
                      "ci": "urn:uvci:01:BG:UFR5PLGKU8WDSZK7#0",
                      "co": "BG",
                      "dn": 2,
                      "dt": "2021-03-09T00:00:00",
                      "is": "Ministry of Health",
                      "ma": "ORG-100030215",
                      "mp": "EU/1/20/1528",
                      "sd": 2,
                      "tg": "840539006",
                      "vp": "J07BX03"
                    }
                  ],
                  "dob": "1978-01-26T00:00:00",
                  "nam": {
                    "fn": "ПЕТКОВ",
                    "gn": "СТАМО ГЕОРГИЕВ",
                    "fnt": "PETKOV",
                    "gnt": "STAMO<GEORGIEV"
                  },
                  "ver": "1.0.0"
                }
              ]
            ]
          }
        ]
      ]
    },
    "Qbd+aDuyiniHXNTQQcDaT9RsriabB1b0cbjq89jY1QNtcguI6HCeGGqh65vddM4LL9LCjPzQ+E0GwKuUaq6b/Q=="
  ]
}
Signature Verified  but Schema has errors [{"instancePath":"","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":[0,1]},"message":"must match exactly one schema in oneOf"}]
```

Decoded REC-NULL-DATETIME.png: 

```
EU Digital Covid Certificate Verifiable QR
{
  "tag": 18,
  "value": [
    { "Map": [ [ 1, -7 ] ] },
    { "Map": [ [ 4, "STPDGKKF4N8" ] ] },
    {
      "Map": [
        [ 1, "BG" ],
        [ 4, 1654179295 ],
        [ 6, 1622643295 ],
        [
          -260,
          {
            "Map": [
              [
                1,
                {
                  "r": [
                    {
                      "ci": "urn:uvci:01:BG:UFR5PLGKU8WDSZK7#0",
                      "co": "BG",
                      "df": "2021-05-11T00:00:00",
                      "du": "2021-10-28T00:00:00",
                      "fr": "2021-05-01T00:00:00",
                      "is": "Ministry of Health",
                      "tg": "840539006"
                    }
                  ],
                  "t": null,
                  "v": null,
                  "dob": "1978-01-26T00:00:00",
                  "nam": {
                    "fn": "ПЕТКОВ",
                    "gn": "СТАМО ГЕОРГИЕВ",
                    "fnt": "PETKOV",
                    "gnt": "STAMO<GEORGIEV"
                  },
                  "ver": "1.0.0"
                }
              ]
            ]
          }
        ]
      ]
    },
    "GU8CRanBXZAAiQcJFpjeJpEBCqo+PzANsAQ+Z2hWBw357gbnN9vOGpt3yOiKWw7s0H+eBYFygJWbDSMm2bhPPA=="
  ]
}
Signature Verified  but Schema has errors [{"instancePath":"","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":[0,1]},"message":"must match exactly one schema in oneOf"}]
```

**Comment by hmeschede** [comment]
Hi Milan, the Read.me contains text related to France, obviously a copy and paste error(??)

**Comment by mkubicek-dtc** [comment]
Hi @RKlaus-tsi 
Please scan with new iOS version.

**Comment by RKlaus-tsi** [comment]
iOS 1.0.5: App shows all 3 codes as valid

**Pull request merged**
