### PR TITLE
ES: Validation Cycle #5

### PR DESCRIPTION
**Pull request by loujensen-dk**

### CODE REVIEW

**Comment by chrloch** [comment]
@loujensen-dk 
Why are there so many regular examples in 1.3? 
I know that we're discussing an extended list of examples but it has not been decided yet. Are you already trying to fulfill it? 
Please for the next cycle, stick to the 3+1 examples that we are used to :-) 
Also, if 1.0.0/TEST is no longer being issued in production, it can be deleted. The repo should only contain structures that are expected to be found in real life

**Comment by loujensen-dk** [comment]
Hi Christian,

There’s a surplus of test examples as they expire, so we’ve uploaded two of each (NAAT and RAT) so they’re valid this week.

Sorry for the confusion,
Louis

From: Christian Loch ***@***.***>
Sent: martes, 10 de agosto de 2021 15:18
To: eu-digital-green-certificates/dcc-quality-assurance ***@***.***>
Cc: Jensen, Louis Enrique Folke ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [eu-digital-green-certificates/dcc-quality-assurance] ES: Validation Cycle #5 (#129)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


@loujensen-dk<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_loujensen-2Ddk&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=JfMyuEFRyG-R9Q5dGH6eaSDOqYLZcLagnDZ0jNNN_ymEXd3wk4-7dAFIhNmndTNu&m=PYTM_WxkUjV2qhV4So7aamYU3S6eH4oa_kvzAx_txWY&s=aX4QafQt_67KdjglD_DrVYcPdOZcqc18cIeJeC-gfx0&e=>
Why are there so many regular examples in 1.3?
I know that we're discussing an extended list of examples but it has not been decided yet. Are you already trying to fulfill it?
Please for the next cycle, stick to the 3+1 examples that we are used to :-)
Also, if 1.0.0/TEST is no longer being issued in production, it can be deleted. The repo should only contain structures that are expected to be found in real life

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eu-2Ddigital-2Dgreen-2Dcertificates_dcc-2Dquality-2Dassurance_pull_129-23issuecomment-2D896020245&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=JfMyuEFRyG-R9Q5dGH6eaSDOqYLZcLagnDZ0jNNN_ymEXd3wk4-7dAFIhNmndTNu&m=PYTM_WxkUjV2qhV4So7aamYU3S6eH4oa_kvzAx_txWY&s=5dcUBD7iwcwnN3-UbwKnmVqHVV2xdgr1RgE1RP0u5Ug&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AUGNPAAUCQU3AXSIR47HT73T4ERHVANCNFSM5BZJ5TQA&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=JfMyuEFRyG-R9Q5dGH6eaSDOqYLZcLagnDZ0jNNN_ymEXd3wk4-7dAFIhNmndTNu&m=PYTM_WxkUjV2qhV4So7aamYU3S6eH4oa_kvzAx_txWY&s=mSjlBCuuOn3C2sbQvyF_bTM-mewNAZqV9gg-2dH98yU&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=JfMyuEFRyG-R9Q5dGH6eaSDOqYLZcLagnDZ0jNNN_ymEXd3wk4-7dAFIhNmndTNu&m=PYTM_WxkUjV2qhV4So7aamYU3S6eH4oa_kvzAx_txWY&s=RI9j12fVjrhbEbA7lTYGDh1C0x0JdKL2YF5BDjf7ZK0&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=JfMyuEFRyG-R9Q5dGH6eaSDOqYLZcLagnDZ0jNNN_ymEXd3wk4-7dAFIhNmndTNu&m=PYTM_WxkUjV2qhV4So7aamYU3S6eH4oa_kvzAx_txWY&s=_oel-QVYq6JT_Btw_ntBb8gc6m_j4fV635TsuqXwA34&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by mkubicek-dtc** [comment]
@loujensen-dk ICAO field contains illegal Ñ character. 

If ES issued certificates with this anomaly, the DCC needs to be provided in the "special cases" directory to skip the validation script and the anomaly needs to be described (number of DCCs issued, period of issued DCCs with this anomaly,..).

**Comment by mkubicek-dtc** [comment]
@loujensen-dk commit contains too many files. Please focus on four types per schema version issued (VAC.png, REC.png, TEST_NAAT.png and TEST_RAT.png) and special cases, if they represent clear deviations from spec and were issued like that in production (incl. description as mentioned in comment above).

**Comment by mkubicek-dtc** [comment]
@loujensen-dk I have renamed NAAT.png->TEST_NAAT.png and RAT.png->TEST_RAT.png to match naming conventions

**Comment by TKlauenberg** [comment]
It seems that the DSC with the KID '9BrghrfaWnU=' is missing in the acceptance environment. Could you please add that certificate or change the certificates signed with that DSC?

The relevant Certs are REC_5.png, VAC_4.png and TEST_NAAT_3.png

**Pull request merged**
