### PR TITLE
upload Morocco (MA) testing files

### PR DESCRIPTION
**Pull request by sbihimohamed**
Dear Team, as requested by mail by TSI-DGC-Onboarding on the OnBoarding process of Morocco (MA) we request to commit Codes for testing.

### CODE REVIEW

**Comment by chrloch** [comment]
Thanks for your submission of codes, please correct the following issues in your request: 

-  The codes in the 1.0.0 directory have a 1.3.0 version tag. If you don't issue any 1.0.0 codes, you should simply omit that directory completely
-  Issuing country is set to IS (Iceland), should be MA
-  File name must begin with "VAC" for vaccination DCC and "TEST" for test DCC

**Comment by sbihimohamed** [comment]
Dear @chrloch  
The issues are corrected, Please let me know in case there's anything we need to change.
Thanks a lot

**Comment by chrloch** [comment]
I'm getting a PASS now on the Android app and in the functional tests in our test suite. 
The automated test's signature validation throws an error now... trying to figure out what the problem is.

**Comment by kerstin-oppermann-tsi** [comment]
iOS 1.1.6.1:

TEST and VAC: **invalid** - cryptographic signature not valid

**Comment by chrloch** [comment]
Dear @sbihimohamed ,

the verification **fails** on the iOS app and in the Python test suite. 

If you have issued codes with this type of signature in production, then we will accept these DCCs as special cases. 

If possible, you should not issue codes with a DSC like this because it will likely not be able to be verified on iOS (and maybe other platforms, depending on the library used)

Error message from python lib: 
self = <ecdsa.ellipticcurve.Point object at 0x7f6274bc89a0>, curve = <ecdsa.ellipticcurve.CurveFp object at 0x7f62786579a0>
x = 323934380341062788...6851809936669714370, y = 124230685314012595...6369055619066004393, order = None

    def __init__(self, curve, x, y, order=None):
        """curve, x, y, order; order (optional) is the order of this point."""
        super(Point, self).__init__()
        self.__curve = curve
        if GMPY:
            self.__x = x and mpz(x)
            self.__y = y and mpz(y)
            self.__order = order and mpz(order)
        else:
            self.__x = x
            self.__y = y
            self.__order = order
        # self.curve is allowed to be None only for INFINITY:
        if self.__curve:
>           assert self.__curve.contains_point(x, y)
E           AssertionError

../venv/lib/python3.8/site-packages/ecdsa/ellipticcurve.py:947: AssertionError

**Comment by sbihimohamed** [comment]
dear @chrloch 
we Uploaded new VAC and TEST certificates, using Document Signers with the Elliptic Curve Digital Signature Algorithm (ECDSA) with NIST-p-256 instead of p-384.

Please let me know in case there's anything we need to change.
Thanks a lot

**Comment by mkubicek-dtc** [comment]
@sbihimohamed DSCs used for signing these DCCs not on ACC: https://github.com/eu-digital-green-certificates/dcc-quality-assurance/pull/159/checks?check_run_id=3527126524

**Comment by sbihimohamed** [comment]
Dear @mkubicek-dtc , I uploaded the following files on MA/1.3.0 directory:

Readme.md
MA/1.3.0/TEST.png 
MA/1.3.0/VAC.png

the DSC used for signing these DCCs is on ACC, could you please check and confirm

**Comment by mkubicek-dtc** [comment]
@sbihimohamed in case the DSC was uploaded very recently it might have not been picked up by the validation script (or more specific the DSC provider) yet. Will re-run the check later.

**Comment by chrloch** [comment]
Dear @sbihimohamed,

the new DCCs pass the script check (the errors in the automated run are from SE, not MA)
We will proceed with the mobile app test

**Comment by chrloch** [comment]
Android 1.1.13 🆗

**Comment by chrloch** [comment]
iOS 1.1.6.1(7) 🆗  (Thanks @RalicaY)

**Pull request merged**
