### PR TITLE
NL Test Cases

### PR DESCRIPTION
**Pull request by ryanbnl**
Test cases for 1.3.0, vaccination and test.
We will hopefully follow with a couple more cases later today.

### CODE REVIEW

**Review by chrloch — CHANGES_REQUESTED** [review]
TEST.PNG is signed with a DSC that may only be used to sign VACs
(DSC allows extended key usage ['1.3.6.1.4.1.0.1847.2021.1.2'] )

**Comment by kerstin-oppermann-tsi** [comment]
in the TEST.png the claimed key is "42" so the app checks the cert as invalid with certificate expired

"Map": [
        [ 1, "NL" ],
        [ 4, 42 ],
        [ 6, 1624877892 ],

**Comment by ryanbnl** [comment]
@chrloch @kerstin-oppermann-tsi I've updated the TEST certificate case. This should be signed by the usage=test certificate, and have a realistic expire date.

**Review by chrloch — CHANGES_REQUESTED** [review]
Expiry Date still shows as Timestamp 42

**Comment by ryanbnl** [comment]
@chrloch now I see how you're testing it :) the VAC cert still had 42, the new case should be fixed. We'll see in a second :)

**Comment by ryanbnl** [comment]
@chrloch @kerstin-oppermann-tsi can you rerun the test script please? :)

**Comment by kerstin-oppermann-tsi** [comment]
@ryanbnl yes the VAC is correct but the TEST.png isn't

**Comment by ryanbnl** [comment]
@kerstin-oppermann-tsi what is wrong with the test.png? Both are marked as correct in the scripts now.

**Comment by chrloch** [comment]
Checked the updated codes with the python script: Both QRs are now OK

**Comment by ryanbnl** [comment]
(I've just updated the branch with the tip of main)

**Review by chrloch — APPROVED** [review]
Both files are OK in pytest suite

**Comment by kerstin-oppermann-tsi** [comment]
@ryanbnl  we have a look at it. Our iOS App says OK to the test.png, the android app does not. We will check what happend.

**Comment by chrloch** [comment]
dcc-quality-assurance/NL/1.3.0/VAC.png]
Allowed Cert Usages: ['1.3.6.1.4.1.0.1847.2021.1.2']
KeyID: DhspllZjSVY=
PASSED
dcc-quality-assurance/NL/1.3.0/TEST.png]
Allowed Cert Usages: ['1.3.6.1.4.1.0.1847.2021.1.1']
KeyID: 428FOlUxNRM=
PASSED

**Comment by ryanbnl** [comment]
@chrloch after mail with Herbert - I've added the recovery cert. Can you retest? I won't add any other examples (they can come next week).

**Comment by chrloch** [comment]
The REC cert looks good 

We have found the problem with the TEST cert too: 
The dr field may not be empty
NL/1.3.0/TEST.png] {1: 'NL', 4: 1640681391, 6: 1625129391, -260: {1: {'ver': '1.3.0', 'dob': '1960-01-01', 'nam': {'fn': 'Bouwer', 'fnt': 'BOUWER', 'gn': 'Bob', 'gnt': 'BOB'}, 't': [{'tg': '840539006', 'tt': 'LP6464-4', 'nm': '', 'ma': '1232', 'sc': '2021-06-30T05:46:50+00:00', **'dr': ''**, 'tr': '260415000', 'tc': 'Some RAT Test Place', 'co': 'NL', 'is': 'Ministry of Health Welfare and Sport', 'ci': 'URN:UCI:01:NL:FNRCHZ3OMRENRKKVERFZ42#7'}]}}}

**Comment by kerstin-oppermann-tsi** [comment]
Ok for the REC.png : both apps say Recovery statement is not valid yet. Thats correct, it seems to be valid from 12th of july.

**Comment by ryanbnl** [comment]
@chrloch 

Thanks, I've put a bug report in to our developers.

DN = Dose Number, your app should be ignoring it if it's included in a Test. The same way it is ignoring the empty NM. The schema specifications make this very clear. If we don't do that then our system is going to be extremely brittle.

**Comment by ryanbnl** [comment]
I've just confirmed that we are issuing certificates like this in production. I'll move it to special cases.

**Comment by ryanbnl** [comment]
@chrloch I've added the case to special cases.

As it conforms to the schema (extra fields are explicitly allowed), I have also left it as our Test certificate case. When we change our issuer I will update that case.

**Pull request merged**
