### PR TITLE
IS update to v1.3 and expiration time

### PR DESCRIPTION
**Pull request by gunnarif**

### CODE REVIEW

**Comment by mkubicek-dtc** [comment]
@gunnarif IS/1.3.0/REC.png contains "du": "0001-01-01" which is not a valid date. See spec:
_"The last date on which the certificate is considered to be valid, assigned by the
certificate issuer. The date MUST NOT be after the date calculated as r/fr +
180 days.
The date MUST be provided in the format YYYY-MM-DD (complete date
without time). Other formats are not supported."_

**Comment by gunnarif** [comment]
@mkubicek-dtc  
fixed

**Comment by TKlauenberg** [comment]
Android 1.1.12 🆗

**Comment by niklasdewes** [comment]
iOS 1.1.6.1 (7) 🆗

**Comment by mkubicek-dtc** [comment]
@gunnarif Just to be sure: Was removal of 1.0.0 intended and are there no 1.0.0 DCCs in the hands of citizens?

**Pull request merged**
