### PR TITLE
UY/1.3.0/README.md

### PR DESCRIPTION
**Pull request by vanrellmichell**

### CODE REVIEW

**Comment by vanrellmichell** [comment]
# UY - Uruguay

* **JSON schema version**: 1.3.0

Used for productive DCCs issuance
* From: 18.11.2021
* Until:

## Test files

### Vaccination

VAC

### Test

TEST

### Recovery

REC

### Special cases and deviations
None

**Comment by vanrellmichell** [comment]
We need to upload our sample QRCodes.
Thanks

**Comment by vanrellmichell** [comment]
Hi,
What should I do so that this Readme appears inside the "UY / 1.3.0 /" folder? 

Regards
Michell

**Comment by chrloch** [comment]
Hi Michell, 

it's important that the PNG files too are in the folder, not just the Readme (we are running check on the content of  the directory, not the references in the readme file)
I've added the files and pushed the change to your pull request. 
Our checks have then discovered some issues: 

image

I hope that the comments are helpful. 

best regards
Christian

**Comment by vanrellmichell** [comment]
Hi, Christian

I understand that the "ma" field is mandatory for RAT type tests, not for NAAT type tests.
Regarding the "ci" field, it appears 2 times since we initially used claim 98 for internal use in the country. This we are leaving aside in the new version.

We are correcting the date of taking the sample in the next shipment of the QR codes.

Finally we are going to correct claim 1 by UY as you indicate.

I will update the pngs of the QRs shortly. 

Regards
Michell

**Comment by vanrellmichell** [comment]
Hi, Christian

The QR codes were updated with the observations reported. 

Regards

**Comment by vanrellmichell** [comment]
Hi, Christian

I'm not sure how to upload the png files separately, I don't think I have the proper permissions.

Can you help me with this issue? 

Regards
Michell

**Comment by chrloch** [comment]
@vanrellmichell 
Hi Michell, 

sorry for the late reply. If the data in claim 98 will exist in your production DCCs, please do not  remove them from the examples. They are an opportunity for other countries to test if they can scan your codes. 

About adding the files: The pull request is created from a branch in your repository, so you can simply add the files to your repo and push them, then they will appear here. But I can also add them to it, if you like. 

best regards
Christian

**Comment by chrloch** [comment]
Hi Michell,

I've pushed the updated codes to your repo (see here https://github.com/vanrellmichell/dcc-quality-assurance/tree/patch-1)
There is only 1 error message left in the check script, complaining about the empty "ma" field. 

Please use a value from this list: 
https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/valuesets/test-manf.json

If you have problems with pushing to your repo, I can do that for you. 
All other checks were good.

BR
Christian

**Comment by vanrellmichell** [comment]
Hi, Christian,

But the attribute "ma" is not required for PCR-type COVID tests. 

imagen

Technical Specifications for EU Digital COVID Certificates
JSON Schema Specification
Schema version: 1.3.0
2021-06-09

This is so or change? 

Thanks

**Comment by chrloch** [comment]
Hi Michell, 

that's right. You can issue a DCC without a "ma" field. But if you have one, it must contain a value from the value set. If your country doesn't use it, please don't include the field at all instead of leaving it empty. 

best regards
Christian

**Comment by vanrellmichell** [comment]
Hi Christian,

I am updating the QR code for the COVID Test, I hope it is correct this
time.

Regards

**Comment by chrloch** [comment]
Android 1.2.4 🆗

**Pull request merged**
