### PR TITLE
ES: New test for 1.0.0 and 1.3.0

### PR DESCRIPTION
**Pull request by Santivicen**

### CODE REVIEW

**Comment by chrloch** [comment]
@Santivicen 
Thank you for your PR.
Please fix the following issues before we can accept it: 
- QR codes for special cases must be in the subfolder ./specialcases
- All DSC public keys (including special cases) to verify the QR codes MUST be available on the ACC environment

If the DSC public keys for TEST_2, TEST_3, REC_2 and VAC_2 cannot be uploaded into the ACC environment, please remove these QR codes.

**Comment by Santivicen** [comment]
> * specialcases

I have create specialcases folders for each version.
DSC public keys must be avaliable before that upload.

Thanks for your help.

**Comment by chrloch** [comment]
PASSED /ES/1.0.0/VAC.png
PASSED /ES/1.0.0/REC.png
PASSED /ES/1.0.0/TEST.png
PASSED /ES/1.3.0/VAC.png
PASSED /ES/1.3.0/REC.png
PASSED /ES/1.3.0/TEST.png
PASSED /ES/1.3.0/specialcases/TEST_1.png


FAILED /ES/1.0.0/specialcases/TEST_2.png] - Failed: KID exist not on acceptance environment
FAILED /ES/1.0.0/specialcases/TEST_3.png] - Failed: KID exist not on acceptance environment
FAILED /ES/1.0.0/specialcases/REC_2.png] - Failed: KID exist not on acceptance environment
FAILED /ES/1.0.0/specialcases/VAC_2.png] - Failed: KID exist not on acceptance environment

**Comment by Santivicen** [comment]
> PASSED /ES/1.0.0/VAC.png
> PASSED /ES/1.0.0/REC.png
> PASSED /ES/1.0.0/TEST.png
> PASSED /ES/1.3.0/VAC.png
> PASSED /ES/1.3.0/REC.png
> PASSED /ES/1.3.0/TEST.png
> PASSED /ES/1.3.0/specialcases/TEST_1.png
> 
> FAILED /ES/1.0.0/specialcases/TEST_2.png] - Failed: KID exist not on acceptance environment
> FAILED /ES/1.0.0/specialcases/TEST_3.png] - Failed: KID exist not on acceptance environment
> FAILED /ES/1.0.0/specialcases/REC_2.png] - Failed: KID exist not on acceptance environment
> FAILED /ES/1.0.0/specialcases/VAC_2.png] - Failed: KID exist not on acceptance environment

I will check that codes to know what is happening with them.

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.0.7.-acc : 

- VAC, REC are **valid**
- TEST, TEST_1 - invalid for **the test date is in the future**

**Comment by Santivicen** [comment]
> Android 1.0.7.-acc :
> 
> * VAC, REC are **valid**
> * TEST, TEST_1 - invalid for **the test date is in the future**

That test are in future to be valid on Monday.

**Comment by RKlaus-tsi** [comment]
iOS 1.0.5: If've scanned the 1.3.0 schema QR-Codes. The 3 normal codes are valid. The special case is shown as invalid because the test is in the future. So all 4 Codes are ok

**Comment by RKlaus-tsi** [comment]
iOS 1.0.5: If've scanned the 1.o.0 schema QR-Codes. The special case TEST_3 is shown as invalid because the test is in the future. All other are shown as valid

**Pull request merged**
