### PR TITLE
TR 1.3.0 Codes

### PR DESCRIPTION
**Pull request by sahinguney**

### CODE REVIEW

**Comment by sahinguney** [comment]
`tests/test_qrqualitycheck.py:61: in valuesets_from_environment
    valuesets[vs['id']] = requests.get(f'{constants.VALUESET_LIST}/{vs["hash"]}').json()['valueSetValues']
E   KeyError: 'valueSetValues'`

According to logs there is something wrong with the parsing of the valuesets returned from the Valueset endpoint. Same error  can be reproduced for any country, so we are not sure if something is wrong with the qr codes or not.

**Comment by libremente** [comment]
Hi @sahinguney, I believe you are hitting this one https://github.com/eu-digital-green-certificates/dcc-quality-assurance/issues/122, same as #119. Could you check this one @mkubicek-dtc? Thank you

**Comment by chrloch** [comment]
There was an error on our valueset distribution yesterady. I'm re-running the checks

**Comment by chrloch** [comment]
Android 1.1.9 🆗

**Comment by RalicaY** [comment]
iOS 1.1.6.1 🆗

**Pull request merged**
