### PR TITLE
ME: Add quality assurance data

### PR DESCRIPTION
**Pull request by sanemalkavian**

### CODE REVIEW

**Comment by chrloch** [comment]
⚠️  Please make the QR codes part of your pull request and don't link to external resources. 
The QR codes cannot be read by the test scripts if they are not part of the pull request.

**Comment by sanemalkavian** [comment]
I added the QR codes and edited README file

**Comment by sanemalkavian** [comment]
Hi,

could you please help me with this? It says that the workflow failed.

Kind regards,
Aleksandar

**Comment by chrloch** [comment]
Please just rename the folder from 1.3.0 to 1.0.0 because that's the schema version being used. 
The value set error is wrong on our side and can be ignored

**Comment by sanemalkavian** [comment]
Thank you for info. I corrected that.

kind regards,
Aleksandar

**Comment by chrloch** [comment]
Hi Aleksandar, 

entries in the "ma" field of vaccine DCCs must come from this list:
https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/main/vaccine-mah-manf.json
not that list: 
https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/main/vaccine-medicinal-product.json
(that goes into the "mp" field)
😉

best regards
Christian

**Comment by sanemalkavian** [comment]
Hi,

we made all the necessary changes.

Let's hope it will go through now.

Kind regards,
Aleksandar

**Comment by chrloch** [comment]
Android 1.2.4 🆗

**Pull request merged**
