### PR TITLE
IT: Validation Cycle #5

### PR DESCRIPTION
**Pull request by libremente**
Hi @mkubicek-dtc @chrloch,
this PR:

* Removes old IT `1.0.0` DCCs;
* Adds new IT `1.0.0` DCCs (new signature and new cases);
* Adds new IT `1.3.0` DCCs.

Please let me know in case there's anything we need to change.
Thanks a lot

### CODE REVIEW

**Comment by mkubicek-dtc** [comment]
@libremente why are you removing 1.0.0 DCCs? This repository should represent all DCC schema versions and variations currently in the wild. By removing 1.0.0 DCCs from this repo you signal that no such are in use by Italian citizens. Is this what you intend?

**Comment by libremente** [comment]
@mkubicek-dtc it's just because we are generating new ones, hopefully we will make it for EOB and I will update this PR accordingly.

**Comment by libremente** [comment]
@mkubicek-dtc `1.0.0` DCCs uploaded, let me know if it's OK for you. Thank you!

**Comment by TKlauenberg** [comment]
Android 1.1.12 🆗

**Comment by niklasdewes** [comment]
iOS 1.1.6.1 (7) 🆗

**Pull request merged**
