### PR TITLE
LV issued certs where facts are from other countries

### PR DESCRIPTION
**Pull request by ArtursMednis**

### CODE REVIEW

**Comment by chrloch** [comment]
Codes scan OK

Not sure if we should include this kind of codes in the collection as they seem legitimate codes within the standard and all countries can issue codes like this and it would just increase the effort for everyone in the validation rounds.

**Comment by ArtursMednis** [comment]
We have issued certificates where vaccinations or tests are performed in other countries not in LV.
So we need to be sure that all countries can verify these certificates.

**Comment by ArtursMednis** [comment]
Hello. What is current status on this?
Do you need more information from us?
Are you considering something? How much time will it take?
Our National Health Service needs to ensure that these kind of certificates can be verified by other countries.

**Comment by RKlaus-tsi** [comment]
iOS 1.1.6 all codes ok

**Pull request merged**
