### PR TITLE
AD - Create Readme.md / upload GC testing files

### PR DESCRIPTION
**Pull request by odelpozo-saas**
Dear Team, as requested by mail by FMB TSI-DGC-Onboarding on the OnBoarding process of Andorra Country (AD) we request to commit this GC Codes for testing.

### CODE REVIEW

**Comment by chrloch** [comment]
Please do not use remote links in the Readme, as the codes should become part of this repo too. 
I've added the files to the PR so that our test script can see them (it does not fetch external links)

Unfortunately, the checks have failed: 
- Certificates are "valid until 1974" which is a bit too far in the past
- Test result values must comply with these value sets: https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/valuesets/test-result.json  Simply "ND" for not detected is not interpreted correctly
- The signer key was not found in the ACC. Please check again if it was really uploaded

**Comment by odelpozo-saas** [comment]
Dear Team, thanks for your feedback, we have uploaded new QR/GC certificates fixing the issues commented previosly, please we need you to validate them again,

Thanks in advance, 
Regards, Oscar.

**Comment by chrloch** [comment]
Hello Oscar (@odelpozo-saas), 

thank you for the update, unfortunately, the codes still don't comply: 
- Payload now has a 1.0.0 version tag but has been put in 1.3.0 folder. Please choose the correct combination which will be used in production in your country
- Please stick to our repo's naming scheme: Vaccination DCCs file name to begin with 'VAC', Test to begin with 'TEST' and Recovery to begin with 'REC'
- Claim Key 4 (valid until) points to year 1974 still. (It's exactly a 4 year epoc - If you want to express that it's *valid for 4 years*, you need to add the number from Claim Key 6 (issued at timestamp) - Both, Key 4 and Key 6 are time stamps, not durations
- Test type "LP-6464-4" must be "LP6464-4" (sorry, computers are stupid)
- The DSCs for the vaccination certificates seem to be not on the ACC environment, only for your Test and Recovery

**Comment by odelpozo-saas** [comment]
Dear Team, thanks for your feedback, we have uploaded new QR/GC certificates fixing the issues commented previosly, please we need you to validate them again,

Thanks in advance,
Regards, Oscar.

**Comment by chrloch** [comment]
Hello Oscar, 

the signature validation passes. 
If you replace the white spaces in the standardized family name with a "<" character, the schema check will pass too.
"TEST-3-Test_Negativo_Valido.png" seems to be a recovery certificate. Is the file name wrong or the file contents? 

best regards
Christian

**Comment by odelpozo-saas** [comment]
Dear Team, thanks for your feedback, we have uploaded new QR/GC certificates fixing the issues commented previosly, please we need you to validate them again,

Thanks in advance,
Regards, Oscar.

**Comment by chrloch** [comment]
Android 1.1.15 🆗

**Pull request merged**
