### PR TITLE
LT: Added 1.3.0 shema DCC's and removed CBOR 0 TAG

### PR DESCRIPTION
**Pull request by Tomas-Alb**
- DCC now are 1.3.0 schema version compliant.
- Added new Test DCC  without CBOR TAG 0.

### CODE REVIEW

**Comment by Tomas-Alb** [comment]
I see that tests failed because KID is missing. I have double-checked and can confirm that they are on acc gateway...
kid
error

**Comment by chrloch** [comment]
**We currently can only check all countries together... the errors do not come from LT and can be ignored for this PR**

**Comment by Tomas-Alb** [comment]
maybe someone deleted our certificates from the gateway? I'm 100 sure that they were there because they has been downloaded to our system from the gateway.

**Comment by Tomas-Alb** [comment]
Please advise how to proceed.

**Comment by Tomas-Alb** [comment]
SORRY!!! we have mixed up test and acc certificates. Closing this pull request. We will generate new QR's

**Review by chrloch — APPROVED** [review]
DSCs for QR codes are now found in ACC environment
Pytest checks PASSD

**Comment by kerstin-oppermann-tsi** [comment]
Now all 3 codes are valid for Android and iOS

**Pull request merged**
