### PR TITLE
TEST DATA FOR TOGO

### PR DESCRIPTION
**Pull request by zenerselom**

### CODE REVIEW

**Comment by chrloch** [comment]
Android 1.2.2 🆗 

Test suite OK too (github execution environment is misconfigured)
tests/test_qrqualitycheck.py::test_if_dsc_exists[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_if_dsc_exists[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_tags[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_tags[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_algorithm[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_algorithm[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_dcc_type_in_payload[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] {1: 'TG', 2: 'Resultat test COVID-19', 6: 1632974163, 5: 1632974163, 4: 1664510163, -260: {1: {'ver': '1.3.0', 'nam': {'fn': 'test', 'fnt': 'TEST', 'gn': 'kpelafiaaa', 'gnt': 'KPELAFIAAA'}, 'dob': '2020-07-28', 't': [{'tg': '840539006', 'tt': 'LP6464-4', 'sc': '2021-09-30T03:56:03Z', 'tr': '260415000', 'tc': 'LAIGE', 'co': 'TG', 'is': "Institut National d'Hygiene", 'ci': 'URN:UVCI:01:TG:LAIGE/20/99999999999'}], 'sex': 'F', 'nat': 'TG', 'idn': 'PASSEPORT<<jejej'}}, 7: b'aS\xb23\xb7\\\x1b\xab\x80J\xa96'}
PASSED
tests/test_qrqualitycheck.py::test_dcc_type_in_payload[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] {1: 'TG', 6: 1632974163, 4: 1664510163, 2: 'Certificat de vaccination COVID-19', -260: {1: {'ver': '1.3.0', 'nam': {'fn': 'Togo', 'fnt': 'TOGO', 'gn': 'test', 'gnt': 'TEST'}, 'dob': '1953-07-21', 'v': [{'tg': '840539006', 'vp': '1119305005', 'mp': 'Covishield', 'ma': 'ORG-100001981', 'dn': 2, 'sd': 2, 'dt': '2021-06-04', 'co': 'TG', 'is': 'INH, Golfe', 'ci': 'URN:UVCI:01:TG:418647694'}], 'meta': {'pr': 'VCC001', 'vcnm': 'Dr AGBETIAFA Koffi', 'bat': '4120Z029', 'ecn': 'TG-2021-03-18-019868-test', 'sex': 'F', 'nat': 'TG', 'idn': 'CNI 43557 Date exp : 08/12/2023'}}}, 7: b'aS\xb23\xb7\\\x1b\xab\x80J\xa96'}
PASSED
tests/test_qrqualitycheck.py::test_payload_version_matches_path_version[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_payload_version_matches_path_version[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_json_schema[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_json_schema[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_verify_signature[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png]
Cert: MIIC2zCCAoGgAwIBAgIUY6Og1gnUqatk3Mf83uN40i+7y20wCgYIKoZIzj0EAwIwgZIxCzAJBgNVBAYTAlRHMREwDwYDVQQIDAhNQVJJVElNRTENMAsGA1UEBwwETE9NRTEOMAwGA1UECgwFTUVOVEQxDDAKBgNVBAsMA0RDQTEYMBYGA1UEAwwPZS1jZXJ0cy5nb3V2LnRnMSkwJwYJKoZIhvcNAQkBFhpzdXBwb3J0X2l0QHN1cHBvcnQuZ291di50ZzAeFw0yMTA5MjgxNTQxNTdaFw0yMzA5MjgxNTQxNTdaMIGDMQswCQYDVQQGEwJURzERMA8GA1UECAwITUFSSVRJTUUxDTALBgNVBAcMBExPTUUxDDAKBgNVBAoMA0lOSDEMMAoGA1UECwwDSU5IMQ8wDQYDVQQDDAZpbmgudGcxJTAjBgkqhkiG9w0BCQEWFndlbWJvby5oYWxhdG9rb0BpbmgudGcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQzKttoyC/OWm3zsLGwGbycMHfd5LYKwQtXjndxOzJBwY9MZTjzPy2atUJJEpATI8IIhYA4tVRENvO816MdR86lo4HBMIG+MA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQUvUcKF9EEhaw8J3b0qS5B6gWKKO8wHwYDVR0jBBgwFoAUZmgWDSW9Ijqk9DHS26FasfKf6rYwOgYDVR0fBDMwMTAvoC2gK4YpaHR0cHM6Ly9lLWNlcnRzLmdvdXYudGcvY3JsL2hjZXJ0L2NvdmlkMTkwMAYDVR0lBCkwJwYLKwYBBAGON49lAQEGCysGAQQBjjePZQECBgsrBgEEAY43j2UBAzAKBggqhkjOPQQDAgNIADBFAiBBcVs2WZSZglbPuQMrdNp3LGajk1xhcUrEoOrdauYWwgIhAJIGNAOnhhcO/jyfohkRbaWIrFnDTkT/S24Ie6sdoTsk
Allowed Cert Usages: ['1.3.6.1.4.1.1847.2021.1.1', '1.3.6.1.4.1.1847.2021.1.2', '1.3.6.1.4.1.1847.2021.1.3']
KeyID: OOMR7vqqmDc=
PASSED
tests/test_qrqualitycheck.py::test_verify_signature[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png]
Cert: MIIC2zCCAoGgAwIBAgIUY6Og1gnUqatk3Mf83uN40i+7y20wCgYIKoZIzj0EAwIwgZIxCzAJBgNVBAYTAlRHMREwDwYDVQQIDAhNQVJJVElNRTENMAsGA1UEBwwETE9NRTEOMAwGA1UECgwFTUVOVEQxDDAKBgNVBAsMA0RDQTEYMBYGA1UEAwwPZS1jZXJ0cy5nb3V2LnRnMSkwJwYJKoZIhvcNAQkBFhpzdXBwb3J0X2l0QHN1cHBvcnQuZ291di50ZzAeFw0yMTA5MjgxNTQxNTdaFw0yMzA5MjgxNTQxNTdaMIGDMQswCQYDVQQGEwJURzERMA8GA1UECAwITUFSSVRJTUUxDTALBgNVBAcMBExPTUUxDDAKBgNVBAoMA0lOSDEMMAoGA1UECwwDSU5IMQ8wDQYDVQQDDAZpbmgudGcxJTAjBgkqhkiG9w0BCQEWFndlbWJvby5oYWxhdG9rb0BpbmgudGcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQzKttoyC/OWm3zsLGwGbycMHfd5LYKwQtXjndxOzJBwY9MZTjzPy2atUJJEpATI8IIhYA4tVRENvO816MdR86lo4HBMIG+MA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQUvUcKF9EEhaw8J3b0qS5B6gWKKO8wHwYDVR0jBBgwFoAUZmgWDSW9Ijqk9DHS26FasfKf6rYwOgYDVR0fBDMwMTAvoC2gK4YpaHR0cHM6Ly9lLWNlcnRzLmdvdXYudGcvY3JsL2hjZXJ0L2NvdmlkMTkwMAYDVR0lBCkwJwYLKwYBBAGON49lAQEGCysGAQQBjjePZQECBgsrBgEEAY43j2UBAzAKBggqhkjOPQQDAgNIADBFAiBBcVs2WZSZglbPuQMrdNp3LGajk1xhcUrEoOrdauYWwgIhAJIGNAOnhhcO/jyfohkRbaWIrFnDTkT/S24Ie6sdoTsk
Allowed Cert Usages: ['1.3.6.1.4.1.1847.2021.1.1', '1.3.6.1.4.1.1847.2021.1.2', '1.3.6.1.4.1.1847.2021.1.3']
KeyID: OOMR7vqqmDc=
PASSED
tests/test_qrqualitycheck.py::test_country_in_path_matches_issuer[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_country_in_path_matches_issuer[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_country_code_formats[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_country_code_formats[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_claim_dates[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_claim_dates[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_valuesets[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\TEST_TG_FINAL.png] PASSED
tests/test_qrqualitycheck.py::test_valuesets[P:\\temp\\dcc-quality-assurance\\TG\\1.3.0\\VAC_TG_FINAL.png] PASSED

**Comment by thomasaugsten** [comment]
@zenerselom Can you please add in the Readme information about the metadata

**Comment by chrloch** [comment]
ℹ️ TG uses following extra data: 
- "meta" attribute with  additional data (e.g. sex, ID#, ...)
- Claim key 7 (CWT ID)
- Claim key 2 (subject) 
see also: RFC 8392

**Comment by chrloch** [comment]
iOS 1.2.0.1 🆗

**Comment by thomasaugsten** [comment]
Full meta list:
    pr: VCC001
    vcnm: Dr AGBETIAFA Koffi
    bat: 4120Z029
    ecn: TG-2021-03-18-019868-test
    sex: F
    nat: TG
    idn: 'CNI 43557 Date exp : 08/12/2023'

**Comment by zenerselom** [comment]
should i add info on readme file?

**Comment by thomasaugsten** [comment]
Yes please

**Pull request merged**
