### PR TITLE
NL Curacao case

### PR DESCRIPTION
**Pull request by ryanbnl**
Added an example of a QR code for Curacao.

### CODE REVIEW

**Comment by chrloch** [comment]
Have these DDCs been issued in production? 

The fields "issued at" and "valid until" are the same value and a negative number. Integer overflow in the issuer application?

 {1: None, 4: -62135596800, 6: -62135596800, -260: {1: {'v': [{'ci': 'URN:UVCI:01:NL:DADFCC47C7334E45A906DB12FD859FB7#1', 'co': 'CW', 'dn': 2, 'dt': '2021-06-11', 'is': 'Ministry of Health Welfare and Sport', 'ma': 'ORG-100031184', 'mp': 'EU/1/20/1507', 'sd': 2, 'tg': '840539006', 'vp': '1119349007'}], 'dob': '1964-01-01', 'nam': {'fn': 'Smith-Jones', 'gn': 'Charles Edward', 'fnt': 'SMITH<JONES', 'gnt': 'CHARLES<EDWARD'}, 'ver': '1.3.0'}}}

**Comment by ryanbnl** [comment]
This DSC is for a new issuer for Curacao. We will also be adding issuers for Aruba and Sint Maarten soon.

It has not been used to issue any certificates in Production: because these are new issuers we would like to first have their certificates validated by everyone in the EU before we upload production certificates.

Thanks for checking, I'll pass the message on and upload new examples once that is fixed.

**Comment by ryanbnl** [comment]
Tomas just pointed out that this PR is still open.

We have abandoned the plan to have the islands implement their own DSC services; we are now providing them with instances of our signing stack as a service.

So to cut a long story short: this PR can be dropped :)

**Comment by ryanbnl** [comment]
Since a week ago we abandoned the per-island custom signer implementation and simply provided our own, so this PR will be closed ;)

**Pull request closed without merging**
