### PR TITLE
Add cyprus 1.3 schema records

### PR DESCRIPTION
**Pull request by lexin10**

### CODE REVIEW

**Comment by RKlaus-tsi** [comment]
iOS 1.1.4.1: Test an VAC invalid because certificate past expiration date , REC= invalid because "exactly one event"

**Comment by mkubicek-dtc** [comment]
@chrloch can you investigate on the "exactly one event" issue? 
Script should check this? https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/0d45b739ca727c11bb9c3cb831a705aae216ba53/tests/test_qrqualitycheck.py#L222

**Comment by chrloch** [comment]
REC =  {4: 1639440000, 6: 1625641844, 1: 'CY', -260: {1: {'r': [{'du': '2021-12-14', 'co': 'CY', 'ci': 'URN:UVCI:V1:CY:P2RVCDIXTUDX6YUJXYQ9UDPNU7', 'is': 'Ministry of Health', 'tg': '840539006', 'fr': '2021-06-17', 'df': '2021-07-01'}], 'nam': {'fnt': 'GARCIA', 'fn': 'Garcia', 'gnt': 'FRANCISCO', 'gn': 'Francisco'}, 'ver': '1.3.0', 'dob': '1982-01-19'}}}

There are no multiple events in this file

**Comment by RKlaus-tsi** [comment]
test with iOS 1.4.1 done again. Now all codes are ok, TST is expired

**Pull request merged**
