### PR TITLE
ES: New tests. 

### PR DESCRIPTION
**Pull request by Santivicen**
Some of test are valid since 01/07 other from 04/07.

On readme you can see more explanations about when are valid each CCD

### CODE REVIEW

**Review by chrloch — APPROVED** [review]
pytest check including special cases passed

**Comment by Santivicen** [comment]
@kerstin-oppermann-tsi @kerstin-oppermann-tsi @RKlaus-tsi, please, could you check if that pull request can be merged in to main to get it in the test cycle?

**Comment by kerstin-oppermann-tsi** [comment]
Tests for commit ae22460:

ES/1.3.0/specialcases/TEST_NAAT_2.png
ES/1.3.0/specialcases/TEST_RAT_2.png
ES/1.0.0/specialcases/TEST_NAAT_2.png
ES/1.0.0/specialcases/TEST_RAT_2.png -> Test date is in the future

Other codes are **valid** for Android

**Comment by Santivicen** [comment]
> Tests for commit [ae22460](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/commit/ae224604f27097a163db6cc8a7476d9e999bf50b):
> 
> ES/1.3.0/specialcases/TEST_NAAT_2.png
> ES/1.3.0/specialcases/TEST_RAT_2.png
> ES/1.0.0/specialcases/TEST_NAAT_2.png
> ES/1.0.0/specialcases/TEST_RAT_2.png -> Test date is in the future
> 
> Other codes are **valid** for Android

It's ok that codes are in future. It was explain on README.

**Comment by kerstin-oppermann-tsi** [comment]
> > Tests for commit [ae22460](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/commit/ae224604f27097a163db6cc8a7476d9e999bf50b):
> > ES/1.3.0/specialcases/TEST_NAAT_2.png
> > ES/1.3.0/specialcases/TEST_RAT_2.png
> > ES/1.0.0/specialcases/TEST_NAAT_2.png
> > ES/1.0.0/specialcases/TEST_RAT_2.png -> Test date is in the future
> > Other codes are **valid** for Android
> 
> It's ok that codes are in future. It was explain on README.

yes I saw this, would it only be mentioned in my comment

**Comment by Santivicen** [comment]
> > > Tests for commit [ae22460](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/commit/ae224604f27097a163db6cc8a7476d9e999bf50b):
> > > ES/1.3.0/specialcases/TEST_NAAT_2.png
> > > ES/1.3.0/specialcases/TEST_RAT_2.png
> > > ES/1.0.0/specialcases/TEST_NAAT_2.png
> > > ES/1.0.0/specialcases/TEST_RAT_2.png -> Test date is in the future
> > > Other codes are **valid** for Android
> > 
> > 
> > It's ok that codes are in future. It was explain on README.
> 
> yes I saw this, would it only be mentioned in my comment

Ahm, sorry. If it's ok @chrloch could you merge it, please?

**Pull request merged**
