### PR TITLE
SG: Add Sample Qr files for vaccination and tests

### PR DESCRIPTION
**Pull request by zawmyolatt**
Changelog:

- Added Vaccination, NAT (Nucleic acid amplification with probe detection) and RAT (Rapid Antigen Test) test certificates Qr sample for Singapore.

### CODE REVIEW

**Comment by mkubicek-dtc** [comment]
@zawmyolatt are you in contact with eHN regarding inclusion of passport numbers in your DCCs?

**Comment by mkubicek-dtc** [comment]
See related eHN issue https://github.com/ehn-dcc-development/ehn-dcc-schema/issues/123

**Comment by zawmyolatt** [comment]
> @zawmyolatt are you in contact with eHN regarding inclusion of passport numbers in your DCCs?

Ah.. i'm not sure about that, let me ask to my team. Our requirement is just want to add our reference data in `meta` as additional key in our data json. Is it not allow ?

**Comment by mkubicek-dtc** [comment]
@zawmyolatt I clarified the extra fields with the EC: The extra fields are not a problem if they do not cause issues with other verifiers. I will merge as soon as the validation script skips the JSON schema check for your DCCs.

**Comment by chrloch** [comment]
@dirkx: Concerning validation, it makes sense to allow validating DCCs from non-EU countries which contain passport or ID card numbers. It is true that EU issuers must not include such information in the DCCs - but that law does not apply to non-EU issuers and we would benefit from being able to validate their DCCs too when their holders are traveling to the EU.

**Comment by dirkx** [comment]
@chrloch I can see your point. The complexity is that the GDPR decrees that if we scan an QR code and start decoding & handling it -- it is processing. Even if we then deceide `not to look at fields'; it still falls under that purview. 

So we cannot 'escape' processing that data (unless the issuing country makes a second Qr, etc).

So at the very least; if one were to allow this to happen - most countries would probably have to revisit their Data Impact Analysis - and confirm that the unanticipated processing of such sensitive data is legal, proportional and done with enough safeguards. And it is bit hard to argue that you need to process it when you do not use it; and it is hard to argue that there are no other, reasonable, technical solutions, as you have just build a compliant a system with the DCC.

As until now - most of those refer back to the Regulation as their basis.  And that would no longer be true if there is a passport, sex or national security number in there.

So the risk here is that we loose the legal basis in quite a few countries due this 'processing'.

**Comment by chrloch** [comment]
I don't agree here, especially regarding the defintion of processing in [the GDPR](https://gdpr-info.eu/art-4-gdpr/). The decoding and decompression happens regardless of  the content. Before decoding, the device cannot know what kind of data is presented.   Therefore there is no way to reject encoded data that contains unwanted information before decoding it. 

A system that processes the data which it is intended for and completely ignores all additional data cannot be considered to be processing the data which has been ignored. In fact, rejecting certificates because they contain surplus personal data would be closer to processing non-allowed data, because in order to identify it, we would have to feed it into some kind of algorithm.

**Comment by chrloch** [comment]
Android 1.1.13 🆗

**Pull request merged**
