### PR TITLE
DK: update of codes

### PR DESCRIPTION
**Pull request by jvitrifork**

### CODE REVIEW

**Review by chrloch — APPROVED** [review]

**Comment by kerstin-oppermann-tsi** [comment]
we have to check the certs intensively

We found out that in the REC.png the "valid until" flag is "2021-12-01" that means valid, 
but the claimed key is [ 4, 1625054001 ] --> Gültig bis 30.06.201 13:53 Uhr and the app checks the cert as invalid with certificate expired

**Comment by jvitrifork** [comment]
@kerstin-oppermann-tsi I can't say what yoy have been looking at, but if I take https://github.com/trifork/dcc-quality-assurance/blob/main/DK/1.3.0/REC.png and throw that at https://zxing.org/w/decode.jspx -> being https://zxing.org/w/decode?u=https%3A%2F%2Fgithub.com%2Ftrifork%2Fdcc-quality-assurance%2Fblob%2Fmain%2FDK%2F1.3.0%2FREC.png%3Fraw%3Dtrue and paste that to https://github.pathcheck.org/debug.html I get the following:

image

-where the claim key 4 has the value of '1627817530' being Sun Aug 01 2021 11:32:10 GMT+0000 - and the 'du' field has the value of '2021-12-12'

Please correct me if I'm wrong, but I can't see any issue in the data.

**Comment by chrloch** [comment]
There must be a copy/paste-error in our comment, the automatic check decodes it as:
REC.png] {1: 'DK', 4: **1627817530**, 6: 1625052730, -260: {1: {'r': [{'ci': 'URN:UVCI:01:DK:CE8D961FB6AF53D8A76A5B04CF4CB7C3#6', 'co': 'DK', 'df': '2021-06-26', **'du': '2021-12-12'**, 'fr': '2021-06-15', 'is': 'Danish Health Data Authority', 'tg': '840539006'}], 'dob': '1901-01-24', 'nam': {'fn': 'Kjær', 'gn': 'Åge Knud', 'fnt': 'KJAER', 'gnt': 'AAGE<KNUD'}, 'ver': '1.3.0'}}}

This is not necessarily an error, but still **2021-08-01** is quite some difference to  **2021-12-12**

I would like to clarifiy with the team how to handle such differences, as I have found them in almost every recovery certificate that we have in the repo.

**Comment by jvitrifork** [comment]
The date *2021-08-01* is the technical expiration of the certificate which for security reasons could/should be way smaller/ealier/have a shorter duration - which is country specific. Preferable as short as possible in order to avoid fraud.  The date *2021-12-12* is more of a clinical/business requirement decided date, specified by the EU specs, that states how long a recovery episode grants the carrier 'immunity'.

The two dates as such are not related besides that the technical date probably never exceeds the 'clinical' date

**Pull request merged**
